"""initial content and secure sessions"""

import sqlalchemy as sa
from alembic import op

revision = "e12bdbbfd255"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("entity", sa.String(length=30), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("image", sa.String(length=300), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "entity IN ('tours','destinations','experiences','journal','gallery','reviews')"
        ),
        sa.CheckConstraint("status IN ('Опубликован','Черновик')"),
        sa.CheckConstraint("version > 0"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity", "slug"),
    )
    op.create_index(op.f("ix_content_entity"), "content", ["entity"], unique=False)
    op.create_table(
        "login_limits",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("until", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "site_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company", sa.String(length=300), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("phone", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=False),
        sa.Column("hero_title", sa.String(length=300), nullable=False),
        sa.Column("hero_description", sa.Text(), nullable=False),
        sa.Column("hero_image", sa.String(length=300), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "role IN ('super_admin','admin','content_manager','manager','operator')"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "articles",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("reading_time", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["content.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.String(length=100), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "content_translations",
        sa.Column("content_id", sa.String(length=100), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("audience", sa.Text(), nullable=False),
        sa.Column("pace", sa.Text(), nullable=False),
        sa.Column("preparation", sa.Text(), nullable=False),
        sa.Column("start_point", sa.String(length=300), nullable=False),
        sa.Column("price_note", sa.Text(), nullable=False),
        sa.Column("stay", sa.Text(), nullable=False),
        sa.Column("transport", sa.Text(), nullable=False),
        sa.Column("season", sa.String(length=300), nullable=False),
        sa.Column("seo_title", sa.String(length=300), nullable=False),
        sa.Column("seo_description", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(["content_id"], ["content.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("content_id", "locale"),
    )
    op.create_table(
        "gallery",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("alt", sa.String(length=300), nullable=False),
        sa.Column("destination_id", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["destination_id"], ["content.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["id"], ["content.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=100), nullable=False),
        sa.Column("csrf", sa.String(length=100), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_table(
        "tours",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("destination_id", sa.String(length=100), nullable=True),
        sa.Column("experience_id", sa.String(length=100), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("max_group", sa.Integer(), nullable=False),
        sa.Column("difficulty", sa.String(length=30), nullable=False),
        sa.CheckConstraint("currency IN ('USD','KGS','EUR')"),
        sa.CheckConstraint("amount >= 0"),
        sa.CheckConstraint("days BETWEEN 1 AND 365"),
        sa.CheckConstraint("max_group BETWEEN 1 AND 100"),
        sa.ForeignKeyConstraint(["destination_id"], ["content.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["experience_id"], ["content.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["id"], ["content.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("author", sa.String(length=300), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("tour_id", sa.String(length=100), nullable=True),
        sa.Column("demo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["content.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tour_id"], ["tours.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tour_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tour_id", sa.String(length=100), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.CheckConstraint("kind IN ('itinerary','included','excluded','faq')"),
        sa.ForeignKeyConstraint(["tour_id"], ["tours.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tour_id", "locale", "kind", "position"),
    )
    op.create_index(op.f("ix_tour_lines_tour_id"), "tour_lines", ["tour_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tour_lines_tour_id"), table_name="tour_lines")
    op.drop_table("tour_lines")
    op.drop_table("reviews")
    op.drop_table("tours")
    op.drop_table("sessions")
    op.drop_table("gallery")
    op.drop_table("content_translations")
    op.drop_table("audit")
    op.drop_table("articles")
    op.drop_table("users")
    op.drop_table("site_settings")
    op.drop_table("login_limits")
    op.drop_index(op.f("ix_content_entity"), table_name="content")
    op.drop_table("content")
    # ### end Alembic commands ###
